import React, { useCallback, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { useAsyncData, usePolling } from './use-api.js';

const labels={queued:'Queued',processing:'Processing',completed:'Completed',failed:'Needs attention','needs-attention':'Needs attention'};
// The task card structure, progress counts and status model are extracted from AutoHub MyTasksPage.
function TaskCard({task,onOpen}) {
  return <article className="user-task-card">
    <div className="user-task-card-line"><div className="user-task-name"><strong>{task.name}</strong><small>{task.toolName}</small></div>
      <span className={`badge ${task.status}`}>{labels[task.status]}</span>
      <button className="secondary" onClick={()=>onOpen(task.id)}>View results <span aria-hidden="true">→</span></button></div>
    <div className="user-task-card-sub"><small>{new Date(task.createdAt).toLocaleString()}</small>
      <progress value={task.progress} max="100" aria-label={`${task.name} progress`}/><span>{task.completedCount} / {task.totalCount} files</span></div>
  </article>;
}
function App() {
  const [key,setKey]=useState(()=>sessionStorage.getItem('autohub-key')??'');
  const [draftKey,setDraftKey]=useState('');
  const [filter,setFilter]=useState('all');
  const [message,setMessage]=useState('');
  const [busy,setBusy]=useState(false);
  const [detail,setDetail]=useState(null);
  const request=useCallback(async(path,method='GET',body)=>{
    const response=await fetch(path,{method,headers:{'x-autohub-browser-key':key,'content-type':'application/json'},body});
    if(!response.ok) throw new Error((await response.json()).error??'Request failed');
    return response;
  },[key]);
  const fetcher=useCallback(async()=>{
    if(!key) return {tasks:[],workers:[]};
    const [tasks,workers]=await Promise.all([request('/api/tasks').then(r=>r.json()),request('/api/workers').then(r=>r.json())]);
    return {tasks,workers};
  },[request,key]);
  const {data,loading,error,refresh,update}=useAsyncData(fetcher,[key]);
  const polling=useCallback(async()=>{try{return await fetcher();}catch(e){setMessage(e.message);throw e;}},[fetcher]);
  usePolling(polling,update,1500,!!key);
  const tasks=data?.tasks??[],workers=data?.workers??[];
  const shown=filter==='all'?tasks:tasks.filter(t=>t.status===filter);
  const open=async id=>{try{setDetail(await(await request(`/api/tasks/${id}`)).json());}catch(e){setMessage(e.message);}};
  const submit=async()=>{
    setBusy(true);setMessage('Uploading synthetic inputs…');
    try {
      const task=await(await request('/api/tasks','POST',JSON.stringify({name:'Synthetic text batch',toolId:'demo-text',items:['welcome.txt','notes.txt','readme.txt']}))).json();
      for(let i=0;i<3;i++) await request(`/api/tasks/${task.id}/items/${i}/input`,'PUT',`A small cluster starts with one spare PC.\nSynthetic document ${i+1}.`);
      await request(`/api/tasks/${task.id}/commit`,'POST','{}');
      setMessage('Submitted. A registered Worker will pick up the task.');refresh();
    }catch(e){setMessage(e.message);}finally{setBusy(false);}
  };
  const download=async idx=>{
    try{
      const response=await request(`/api/tasks/${detail.id}/items/${idx}/result`);
      const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`result-${idx}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
    }catch(e){setMessage(e.message);}
  };
  const retry=async idx=>{
    setBusy(true);
    try{await request(`/api/tasks/${detail.id}/items/${idx}/retry`,'POST','{}');await open(detail.id);refresh();}
    catch(e){setMessage(e.message);}finally{setBusy(false);}
  };
  return <div className="shell">
    <aside><a className="brand" href="/">A<span>AutoHub<small>WINDOWS WORKER CLUSTER</small></span></a><nav aria-label="Primary"><a href="#workbench" className="selected">Workbench</a><a href="#workers">Workers <span>{workers.length}</span></a></nav><div className="aside-bottom"><strong>Community · v0.1</strong><p>Self-hosted. Local first.<br/>Your machines, your tasks.</p></div></aside>
    <main id="workbench"><header><span className="eyebrow">YOUR SMALL WORKER CLUSTER</span><span className="edition">Local / trusted team</span></header>
      <div className="heading"><div><h1>Make spare PCs useful.</h1><p>Submit a batch. Follow the work. Collect the results.</p></div><button disabled={!key||busy} onClick={submit}>{busy?'Submitting…':'+ Run synthetic demo'}</button></div>
      {!key&&<form className="connect" onSubmit={e=>{e.preventDefault();sessionStorage.setItem('autohub-key',draftKey);setKey(draftKey);}}><label htmlFor="access-key">Connect to your local Server</label><p>Paste the browser key generated by setup or shown by your running demo.</p><div><input id="access-key" type="password" value={draftKey} onChange={e=>setDraftKey(e.target.value)} required autoComplete="off"/><button>Connect</button></div></form>}
      {key&&<div className="connection"><span>Keys stay in this browser session.</span><button className="text-button" onClick={()=>{sessionStorage.removeItem('autohub-key');setKey('');setDetail(null);}}>Disconnect</button></div>}
      <p className="notice" role="status">{error?.message??message}</p>
      <section className="stats" aria-label="Cluster summary"><div><small>AVAILABLE WORKERS</small><strong>{workers.filter(w=>w.status!=='offline').length}<em>online</em></strong></div><div><small>IN PROGRESS</small><strong>{tasks.filter(t=>t.status==='processing').length}<em>tasks</em></strong></div><div><small>COMPLETED</small><strong>{tasks.filter(t=>t.status==='completed').length}<em>batches</em></strong></div></section>
      <section className="tasks"><div className="section-heading"><h2>Task activity</h2><button className="text-button" onClick={refresh}>Refresh</button></div><div className="filters" role="group" aria-label="Task filter">{['all','queued','processing','completed','failed'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f==='all'?'All tasks':labels[f]}</button>)}</div>
        {loading&&!tasks.length&&<p>Loading tasks…</p>}{shown.map(t=><TaskCard key={t.id} task={t} onOpen={open}/>)}{!loading&&!shown.length&&<p className="empty">No tasks here yet. Start with a synthetic demo.</p>}
      </section>
      {detail&&<section className="detail" aria-label="Task results"><div className="section-heading"><h2>{detail.name}</h2><button className="text-button" onClick={()=>setDetail(null)}>Close results</button></div><button className="text-button" onClick={()=>open(detail.id)}>Refresh item status</button>{detail.records.map(i=><div className="item" key={i.idx}><span>{i.name}<small>{i.error}</small></span><span>{i.status}</span>{i.status==='done'&&<button className="secondary" onClick={()=>download(i.idx)}>Download</button>}{i.status==='failed'&&<button disabled={busy} className="secondary" onClick={()=>retry(i.idx)}>Retry item</button>}</div>)}</section>}
      <section id="workers"><div className="section-heading"><h2>Worker pool</h2><span>Task-level scheduling</span></div><div className="workers">{workers.map(w=><article key={w.id}><div className="worker-mark" aria-hidden="true">PC</div><div><strong>{w.id}</strong><small>{w.tools.join(', ')}</small></div><span className={`badge ${w.status==='offline'?'failed':'completed'}`}>{w.status}</span></article>)}{!workers.length&&<p className="empty">Start a Demo Worker to make this cluster ready.</p>}</div></section>
      <footer>Loopback by default · No cloud account · At-least-once recovery</footer>
    </main>
  </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
